import React from "react";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service – Tralance App & Website",
  description: "These Terms of Service apply to the Tralance app/website by DmilX (Sachin Kumar). Learn about licensing, usage rights, and disclaimers for our offline finance tool.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsOfServicePage() {

  return (
    <main className="bg-white dark:bg-[#030303] min-h-screen py-16 md:py-24 font-sans text-slate-800 dark:text-slate-300 selection:bg-blue-100 dark:selection:bg-blue-900">
      <div className="max-w-[850px] mx-auto px-5 sm:px-6 lg:px-8">
        
        {/* Header */}
        <header className="mb-12 border-b border-slate-200/60 dark:border-white/5 pb-10">
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-slate-500 dark:text-slate-400 font-medium text-[15px]">
            Last Updated: August 3, 2026
          </p>
        </header>

        <div className="flex flex-col md:flex-row gap-12 md:gap-16">
          
          <div className="w-full">
          

            {/* Content Sections */}
            <article className="prose prose-slate dark:prose-invert prose-headings:font-bold prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-6 prose-p:text-[15px] prose-p:leading-relaxed prose-p:mb-5 prose-li:text-[15px] max-w-none">
              
              <section id="acceptance-of-terms" className="scroll-mt-24">
                <h2>1. Acceptance of Terms</h2>
                <p>
                  These Terms of Service govern the use of the Tralance app/website. Tralance is operated by DmilX, a sole proprietorship of Sachin Kumar. By using Tralance, you agree to these terms.
                </p>
                <p>
                  By accessing, browsing, or utilizing the website located at tralance.pro (the &quot;Website&quot;), you acknowledge that you have read, understood, and agreed to be legally bound by these Terms of Service. If you do not agree to any of these terms, you are expressly prohibited from using the Website and must discontinue use immediately.
                </p>
              </section>

              <section id="about-this-website" className="scroll-mt-24">
                <h2>2. About This Website</h2>
                <p>
                  Tralance is an informational platform providing free browser-based productivity tools (such as rate calculators and academic planners) and editorial content (such as blog articles) intended for freelancers and students. These Terms of Service apply strictly to the Website and do not govern any downloadable software or separate applications associated with the Tralance brand, unless explicitly stated.
                </p>
              </section>

              <section id="eligibility" className="scroll-mt-24">
                <h2>3. Eligibility</h2>
                <p>
                  You must be at least 13 years of age to use this Website. By using the Website, you represent and warrant that you meet this age requirement and have the legal capacity to enter into these Terms of Service. If you are under the age of majority in your jurisdiction, you must have the consent of a parent or guardian.
                </p>
              </section>

              <section id="website-usage-rules" className="scroll-mt-24">
                <h2>4. Website Usage Rules</h2>
                <p>
                  You agree to use the Website solely for lawful purposes. You shall not engage in any activity that interrupts, damages, or impairs the functionality of the Website, including but not limited to transmitting viruses, utilizing automated scripts, attempting unauthorized access, or violating any local, national, or international laws.
                </p>
              </section>

              <section id="free-tools-disclaimer" className="scroll-mt-24">
                <h2>5. Free Tools Disclaimer</h2>
                <p>
                  The free productivity tools, including but not limited to the Freelancer Rate Calculator and the CGPA Planner, are provided strictly for educational and informational purposes. While we strive to ensure the accuracy of the algorithms, the mathematical results generated by these tools should not be construed as definitive financial, tax, or official academic advice. You are solely responsible for verifying the accuracy of any calculations prior to making financial or educational decisions.
                </p>
              </section>

              <section id="blog-content-disclaimer" className="scroll-mt-24">
                <h2>6. Blog Content Disclaimer</h2>
                <p>
                  The articles and publications featured on the Tralance blog represent the personal opinions and experiences of their respective authors. This content is provided for informational purposes only. We do not guarantee the completeness, reliability, or accuracy of any information presented on the blog, and any action you take based upon this information is strictly at your own risk.
                </p>
              </section>

              <section id="intellectual-property" className="scroll-mt-24">
                <h2>7. Intellectual Property</h2>
                <p>
                  All content, design, code, graphics, logos, and original text on this Website are the exclusive intellectual property of Tralance and are protected by applicable copyright, trademark, and intellectual property laws. You may not reproduce, distribute, modify, or create derivative works of any Website content without our prior express written permission.
                </p>
              </section>

              <section id="user-responsibilities" className="scroll-mt-24">
                <h2>8. User Responsibilities</h2>
                <p>
                  When utilizing the Website, you bear full responsibility for the data you input into our local, browser-based calculators. Because the tools function strictly offline via your web browser, we do not store, recover, or monitor your inputs. You are solely responsible for maintaining the privacy of any personal data you type into the Website while using shared or public devices.
                </p>
              </section>

              <section id="external-links" className="scroll-mt-24">
                <h2>9. External Links</h2>
                <p>
                  The Website may contain links to third-party websites or services that are not owned or controlled by Tralance. We assume no responsibility for the content, privacy policies, or practices of any third-party websites. You acknowledge and agree that Tralance shall not be held liable for any damage or loss caused by your reliance on any such external content or services.
                </p>
              </section>

              <section id="third-party-services" className="scroll-mt-24">
                <h2>10. Third-Party Services</h2>
                <p>
                  We utilize various third-party services for website analytics, hosting, and performance optimization. Your interaction with the Website may involve data processing by these providers in accordance with their respective privacy policies and terms of service.
                </p>
              </section>

              <section id="google-adsense" className="scroll-mt-24">
                <h2>11. Google AdSense & Advertising</h2>
                <p>
                  The Website features third-party advertisements delivered via Google AdSense. Google utilizes cookies to serve tailored advertisements based on your visits to this and other websites across the internet. We do not endorse the products or services displayed in these advertisements. You may opt out of personalized advertising by visiting Google&apos;s Ads Settings portal.
                </p>
              </section>

              <section id="limitation-of-liability" className="scroll-mt-24">
                <h2>12. Limitation of Liability</h2>
                <p>
                  To the maximum extent permitted by applicable law, in no event shall Tralance, its developers, authors, or affiliates be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or inability to access the Website, or from any reliance placed on the information or tools provided on the Website.
                </p>
              </section>

              <section id="disclaimer-of-warranties" className="scroll-mt-24">
                <h2>13. Disclaimer of Warranties</h2>
                <p>
                  The Website and all materials contained therein are provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis, without warranties of any kind, either express or implied. We expressly disclaim any warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not guarantee that the Website will be uninterrupted, error-free, or entirely secure.
                </p>
              </section>

              <section id="indemnification" className="scroll-mt-24">
                <h2>14. Indemnification</h2>
                <p>
                  You agree to defend, indemnify, and hold harmless Tralance and its personnel from and against any and all claims, damages, obligations, losses, liabilities, costs, or debts, and expenses (including attorney&apos;s fees) arising from your use of and access to the Website, or your violation of any term of these Terms of Service.
                </p>
              </section>

              <section id="termination" className="scroll-mt-24">
                <h2>15. Termination</h2>
                <p>
                  We reserve the right to terminate or suspend your access to the Website immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms of Service. Upon termination, your right to use the Website will immediately cease.
                </p>
              </section>

              <section id="changes-to-terms" className="scroll-mt-24">
                <h2>16. Changes to These Terms</h2>
                <p>
                  We reserve the exclusive right to modify or replace these Terms of Service at any time. We will indicate that updates have been made by altering the &quot;Last Updated&quot; date at the top of this document. It is your responsibility to review these Terms periodically. Your continued use of the Website following the posting of any changes constitutes acceptance of those changes.
                </p>
              </section>

              <section id="governing-law" className="scroll-mt-24">
                <h2>17. Governing Law</h2>
                <p>
                  These Terms shall be governed and construed in accordance with applicable laws, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
                </p>
              </section>

              <section id="contact-information" className="scroll-mt-24 mb-16">
                <h2>18. Contact Information</h2>
                <p>
                  If you have any questions or concerns regarding these Terms of Service, please contact us by visiting the <Link href="/contact" className="text-blue-600 dark:text-blue-400 hover:underline">Contact page</Link> on our Website.
                </p>
              </section>

            </article>
          </div>
        </div>
      </div>
    </main>
  );
}
